# ClusterSecretStore — connects External Secrets Operator to Infisical
# All ExternalSecret resources across namespaces reference this store.
#
# Prerequisites:
#   1. Infisical must be running (apps/infisical.yaml)
#   2. A machine identity must be created in Infisical with Universal Auth
#   3. The client-id and client-secret must be stored in the secret below
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
# The infisical-machine-identity Secret is managed by Pulumi (secrets.enc.yaml)
# and should NOT be defined here to avoid overwriting real credentials.
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-machine-identity
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: infisical-machine-identity
            namespace: external-secrets
      # Internal service URL — Infisical runs in-cluster
      hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
      secretsScope:
        projectSlug: homelab
        environmentSlug: prod
        secretsPath: /
