# Onchain Monitor — Go backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onchain-monitor-api
  namespace: onchain-monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onchain-monitor-api
  namespace: onchain-monitor
  labels:
    app: onchain-monitor-api
    app.kubernetes.io/name: onchain-monitor-api
    app.kubernetes.io/part-of: onchain-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onchain-monitor-api
  template:
    metadata:
      labels:
        app: onchain-monitor-api
        app.kubernetes.io/name: onchain-monitor-api
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: onchain-monitor-api
      containers:
        - name: onchain-monitor-api
          image: ghcr.io/web3-frozen/onchain-monitor
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: onchain-monitor-db-app
                  key: uri
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-token
                  key: token
            - name: FRONTEND_ORIGIN
              value: "https://monitoring.example.com"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: onchain-monitor-api
  namespace: onchain-monitor
  labels:
    app: onchain-monitor-api
spec:
  selector:
    app: onchain-monitor-api
  ports:
    - port: 8080
      targetPort: http
      name: http
      protocol: TCP
