# ExternalSecret — syncs Telegram bot token from Infisical
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-bot-token
  namespace: onchain-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: telegram-bot-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: TELEGRAM_BOT_TOKEN
