# ExternalSecret — syncs Redis password from Infisical for onchain-monitor.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-password
  namespace: onchain-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: redis-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: REDIS_PASSWORD
