apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Bootstrap secret generation (PreSync hook — runs once)
    - repoURL: https://github.com/web3-frozen/homelab-apps.git
      targetRevision: main
      path: platform/infisical
    # Infisical Helm chart
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
      chart: infisical-standalone
      targetRevision: "1.7.2"
      helm:
        valuesObject:
          # Use built-in PostgreSQL and Redis for homelab (simplicity)
          postgresql:
            enabled: true
          redis:
            enabled: true
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
