# Grafana Loki — Log aggregation backend
# Paired with Promtail for collection and Grafana for querying.
# Uses monolithic mode (single binary) — suitable for homelab scale.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.24.0"
    helm:
      valuesObject:
        # Single-binary deployment (monolithic) — simple for homelab
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
        singleBinary:
          replicas: 1
          persistence:
            size: 10Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        # Disable components not needed in monolithic mode
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        gateway:
          enabled: false
        # Monitoring
        monitoring:
          serviceMonitor:
            enabled: true
        # Disable test pod
        test:
          enabled: false
        # Chunk cache for better performance
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        lokiCanary:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
