# Shared Redis (Bitnami) for application caching
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: redis
    targetRevision: "18.9.0"
    helm:
      valuesObject:
        architecture: standalone
        auth:
          enabled: true
          existingSecret: redis-password
          existingSecretPasswordKey: password
        serviceAccount:
          create: true
        master:
          persistence:
            size: 2Gi
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
        metrics:
          enabled: true
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          serviceMonitor:
            enabled: true
        # Bootstrap: generate password secret if missing
        extraDeploy:
          - apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: redis-bootstrap
              annotations:
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              name: redis-bootstrap
              annotations:
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
            rules:
              - apiGroups: [""]
                resources: ["secrets"]
                verbs: ["get", "create"]
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: redis-bootstrap
              annotations:
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
            subjects:
              - kind: ServiceAccount
                name: redis-bootstrap
            roleRef:
              kind: Role
              name: redis-bootstrap
              apiGroup: rbac.authorization.k8s.io
          - apiVersion: batch/v1
            kind: Job
            metadata:
              name: redis-bootstrap-password
              annotations:
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
            spec:
              backoffLimit: 3
              template:
                metadata:
                  labels:
                    app: redis-bootstrap
                spec:
                  serviceAccountName: redis-bootstrap
                  restartPolicy: Never
                  containers:
                    - name: bootstrap
                      image: alpine:3.21
                      resources:
                        requests:
                          cpu: 50m
                          memory: 64Mi
                        limits:
                          cpu: 200m
                          memory: 128Mi
                      command:
                        - sh
                        - -ce
                        - |
                          apk add --no-cache openssl curl > /dev/null 2>&1
                          curl -sLo /usr/local/bin/kubectl \
                            "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                          chmod +x /usr/local/bin/kubectl
                          if kubectl get secret redis-password -n redis > /dev/null 2>&1; then
                            echo "Secret redis-password already exists, skipping."
                            exit 0
                          fi
                          PASSWORD=$(openssl rand -base64 24)
                          kubectl create secret generic redis-password \
                            --namespace redis \
                            --from-literal=password="$PASSWORD"
                          echo "Redis password secret created."
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
