# Strimzi Kafka Operator + KRaft-mode Kafka cluster
# Provides Kafka for async event streaming (audit logs, notifications)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: "0.44.0"
    helm:
      valuesObject:
        watchAnyNamespace: true
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: "1"
            memory: 768Mi
        extraEnvs:
          - name: JAVA_OPTS
            value: "-Xms128m -Xmx384m -Dlog4j2.configurationFile=file:/opt/strimzi/custom-config/log4j2.properties -Dvertx.cacheDirBase=/tmp/vertx-cache -Djava.security.egd=file:/dev/./urandom -XX:+ExitOnOutOfMemoryError"
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
