apiVersion: v1
kind: ConfigMap
metadata:
  name: defi-lending-frontend-nginx
  namespace: defi-lending
data:
  default.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://defi-lending-api.defi-lending.svc.cluster.local:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: defi-lending-frontend
  namespace: defi-lending
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defi-lending-frontend
  namespace: defi-lending
spec:
  replicas: 2
  selector:
    matchLabels:
      app: defi-lending-frontend
  template:
    metadata:
      labels:
        app: defi-lending-frontend
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: defi-lending-frontend
      containers:
        - name: defi-lending-frontend
          image: ghcr.io/web3-frozen/defi-lending-frontend
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: nginx-config
          configMap:
            name: defi-lending-frontend-nginx
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: defi-lending-frontend
  namespace: defi-lending
spec:
  selector:
    app: defi-lending-frontend
  ports:
    - port: 80
      targetPort: http
      name: http
