# ExternalSecret — syncs Redis password from Infisical into a K8s Secret.
# Requires the "infisical" ClusterSecretStore and a matching secret
# in the Infisical project under the configured environment.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-password
  namespace: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: redis-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: REDIS_PASSWORD
